apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec: 
  type: LoadBalancer
  selector:
    env: Prod # This is Labels from Pod-1.yaml file to match the Pods
  ports:
  - name: http 
    port: 80  #Service Port
    targetPort: 80 #Container Port