apiVersion: v1
kind: Service
metadata:
  name: my-backend-service  # need to exactly same as it is been used in Frontend Nginx proxy pass
  labels: 
    app: backend-restapp
    tier: backend
spec:
# type: ClusterIp is the default Service so no need to specifically  define it 
  selector: 
    app: backend-restapp
  ports:  
  - name: http
    port: 8080 # Exposed port
    targetPort: 8080 # Container Port